// Telegram bot skeleton generated by the scaffold.
// Set TELEGRAM_BOT_TOKEN in your environment before running.
// npm install telegraf (not installed automatically — this is a starting point).
import { Telegraf } from 'telegraf';

const bot = new Telegraf(process.env.TELEGRAM_BOT_TOKEN);

bot.start((ctx) => ctx.reply('Hello from your generated agent!'));
bot.on('message', (ctx) => ctx.reply('TODO: connect this to your agent logic.'));

bot.launch();
