// Web chat interface skeleton generated by the scaffold.
// Expects a local API endpoint at /api/chat — implement that endpoint
// yourself using the agent's own prompts/memory/module configuration.
async function sendMessage(text) {
  const response = await fetch('/api/chat', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ message: text }),
  });
  return response.json();
}
// TODO: wire this up to your chosen frontend framework or vanilla DOM code.
