// Discord bot skeleton generated by the scaffold.
// Set DISCORD_BOT_TOKEN in your environment before running.
// npm install discord.js (not installed automatically — this is a starting point).
import { Client, GatewayIntentBits } from 'discord.js';

const client = new Client({ intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages] });

client.once('ready', () => {
  console.log(`Logged in as ${client.user.tag}`);
});

client.on('messageCreate', async (message) => {
  if (message.author.bot) return;
  // TODO: connect this to the agent's own prompt/memory logic.
});

client.login(process.env.DISCORD_BOT_TOKEN);
